# Generated by Django 4.2.1 on 2023-06-11 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('acousticness', models.FloatField(blank=True, null=True)),
                ('album_id', models.UUIDField(blank=True, null=True)),
                ('analysis_url', models.URLField(blank=True, null=True)),
                ('artists_id', models.CharField(blank=True, max_length=500, null=True)),
                ('available_markets', models.CharField(blank=True, max_length=512, null=True)),
                ('country', models.CharField(blank=True, max_length=5, null=True)),
                ('danceability', models.FloatField(blank=True, null=True)),
                ('disc_number', models.IntegerField(blank=True, null=True)),
                ('duration_ms', models.IntegerField(blank=True, null=True)),
                ('enerfy', models.FloatField(blank=True, null=True)),
                ('href', models.URLField(blank=True, null=True)),
                ('uuid', models.UUIDField(blank=True, null=True)),
                ('instrumentalness', models.FloatField(blank=True, null=True)),
                ('key', models.FloatField(blank=True, null=True)),
                ('liveness', models.FloatField(blank=True, null=True)),
                ('loudness', models.FloatField(blank=True, null=True)),
                ('lyrics', models.TextField(blank=True, null=True)),
                ('mode', models.FloatField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('playlist', models.CharField(blank=True, max_length=256, null=True)),
                ('popularity', models.FloatField(blank=True, null=True)),
                ('preview_url', models.URLField(blank=True, null=True)),
                ('speechiness', models.FloatField(blank=True, null=True)),
                ('tempo', models.FloatField(blank=True, null=True)),
                ('time_signature', models.FloatField(blank=True, null=True)),
                ('track_href', models.URLField(blank=True, null=True)),
                ('track_name_prev', models.CharField(blank=True, max_length=128, null=True)),
                ('track_number', models.IntegerField(blank=True, null=True)),
                ('uri', models.CharField(blank=True, max_length=256, null=True)),
                ('valence', models.FloatField(blank=True, null=True)),
                ('cluster', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
