# Generated by Django 4.2.1 on 2023-06-11 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='track',
            old_name='cluster',
            new_name='cluster_number',
        ),
        migrations.RenameField(
            model_name='track',
            old_name='enerfy',
            new_name='energy',
        ),
        migrations.AlterField(
            model_name='track',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
