# Generated by Django 4.2.1 on 2023-06-11 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0002_rename_cluster_track_cluster_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='album_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='uuid',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
