version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    container_name: django-docker-app
    volumes:
      - ./:/webapp/
      - ./files:/appfiles
    depends_on:
      - postgres
  postgres:
    image: postgis/postgis
    container_name: django-docker-db
    volumes:
      - pgdata:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - "5432:5432"
    restart: unless-stopped
  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    container_name: django-docker-proxy
    ports:
      - "8080:8080"
    volumes:
      - ./docker/nginx/dev.conf:/etc/nginx/conf.d/default.conf
      - ./files/static/:/appfiles/static/
      - ./files/media/:/appfiles/media/
    restart: unless-stopped
    depends_on:
      - app
      - postgres
      - redis
  redis:
    image: redis:alpine
    container_name: django-docker-redis
    restart: unless-stopped
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server --include /usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"
  celery:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    container_name: django-docker-celery
    command: celery -A xpotify worker -l info
    volumes:
      - ./:/webapp/
    env_file:
      - .env
    depends_on:
      - postgres
      - redis

  celery-beat:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    container_name: django-docker-celery-beat
    command: celery -A xpotify beat -l info
    volumes:
      - ./:/webapp/
    env_file:
      - .env
    depends_on:
      - postgres
      - redis

volumes:
  pgdata:
